export enum GatewayEnvironment {
    LABS = "LABS",
    PRODUCTION = "PRODUCTION"
}
export enum NetworkSource {
    WIFI = "WIFI",
    EHTERNET = "EHTERNET",
    SIM = "SIM"
}
export enum ResponseCallbackType {
    RES_TYPE_GATEWAY = "GATEWAY_CONNECTION",
    RES_TYPE_MARCHENT_AUTHENTICATED = "MARCHENT_AUTHENTICATED",
    RES_TYPE_PAYMENT_WISEPAD_CONNECTION = "PAYMENT_WISEPAD_CONNECTION",
    RES_TYPE_PAYMENT_CARD_PROCESS = "PAYMENT_CARD_PROCESS",
    RES_TYPE_PAYMENT_CARD_PROCESS_RESULTS = "PAYMENT_CARD_PROCESS_RESULTS",
    RES_TYPE_PAYMENT_ERROR = "PAYMENT_ERROR",
    RES_TYPE_PAYMENT_APPROVED = "PAYMENT_APPROVED",
    RES_TYPE_PAYMENT_DISPLAY_TEXT = "PAYMENT_DISPLAY_TEXT",
    RES_TYPE_DEVICE_DISCONNECT = "DEVICE_DISCONNECT ",
    RES_TYPE_NO_CONFIG = "NO_CONFIG",
    RES_TYPE_EXISTING_SESSION_FOUND = "EXISTING_SESSION_FOUND"
}

export enum WisePadConnection {
    CONNECTING = "WisePadConnection_CONNECTING",
    DIS_CONNECTED = "WisePadConnection_DIS_CONNECTED",
    CONNECTED = "WisePadConnection_CONNECTED",
    NOT_CONNECTED = "WisePadConnection_NOT_CONNECTED",
    DEVICE_NOTFOUND = "WisePadConnection_DEVICE_NOTFOUND",
    DEVICE_DETECTED = "WisePadConnection_DEVICE_DETECTED",
    BLUETOOTH_SWITCHEDOFF = "WisePadConnection_BLUETOOTH_SWITCHEDOFF",
    BLUETOOTH_DISABLED = "WisePadConnection_BLUETOOTH_DISABLED",
    MULTIPLE_PAIRED_DEVCIES_FOUND = "WisePadConnection_MULTIPLE_PAIRED_DEVCIES_FOUND",
    NO_PAIRED_DEVICES_FOUND = "WisePadConnection_NO_PAIRED_DEVICES_FOUND",
    SCANNING = "WisePadConnection_SCANNING",
    FAIL_TO_START_BT = "WisePadConnection_FAIL_TO_START_BT"
}

export enum CardProcessResults {
    NO_CARD = "NO_CARD",
    INSERTED_CARD = "INSERTED_CARD",
    NOT_ICC = "NOT_ICC",
    BAD_SWIPE = "BAD_SWIPE",
    MSR = "MSR",
    MAG_HEAD_FAIL = "MAG_HEAD_FAIL",
    USE_ICC_CARD = "USE_ICC_CARD",
    TAP_CARD_DETECTED = "TAP_CARD_DETECTED",
    MANUAL_PAN_ENTRY = "MANUAL_PAN_ENTRY",
    CANCEL_CHECK_CARD = "CANCEL_CHECK_CARD",
    PIN_ENTERED = "PIN_ENTERED",
    PIN_BYPASS = "PIN_BYPASS",
    PIN_CANCEL = "PIN_CANCEL",
    PIN_TIMEOUT = "PIN_TIMEOUT",
    PIN_WRONG_PIN_LENGTH = "PIN_WRONG_PIN_LENGTH",
    PIN_INCORRECT_PIN = "PIN_INCORRECT_PIN",
    PIN_UNKNOWN_ERROR = "PIN_UNKNOWN_ERROR",
    PIN_Asterisk = "PIN_Asterisk",
    ON_REQUEST_ONLINEPROCESS = "ON_REQUEST_ONLINEPROCESS",
    TRANSACTION_TERMINATED = "TRANSACTION_TERMINATED",
    TRANSACTION_DECLINED = "TRANSACTION_DECLINED",
    TRANSACTION_CANCELED_OR_TIMEOUT = "TRANSACTION_CANCELED_OR_TIMEOUT",
    TRANSACTION_CAPK_FAIL = "TRANSACTION_CAPK_FAIL",
    TRANSACTION_NOT_ICC = "TRANSACTION_NOT_ICC",
    TRANSACTION_SELECT_APP_FAIL = "TRANSACTION_SELECT_APP_FAIL",
    TRANSACTION_DEVICE_ERROR = "TRANSACTION_DEVICE_ERROR",
    TRANSACTION_APPLICATION_BLOCKED = "TRANSACTION_APPLICATION_BLOCKED",
    TRANSACTION_ICC_CARD_REMOVED = "TRANSACTION_ICC_CARD_REMOVED",
    TRANSACTION_CARD_BLOCKED = "TRANSACTION_CARD_BLOCKED",
    TRANSACTION_CARD_NOT_SUPPORTED = "TRANSACTION_CARD_NOT_SUPPORTED",
    TRANSACTION_CONDITION_NOT_SATISFIED = "TRANSACTION_CONDITION_NOT_SATISFIED",
    TRANSACTION_INVALID_ICC_DATA = "TRANSACTION_INVALID_ICC_DATA",
    TRANSACTION_MISSING_MANDATORY_DATA = "TRANSACTION_MISSING_MANDATORY_DATA",
    TRANSACTION_NO_EMV_APPS = "TRANSACTION_NO_EMV_APPS",
    TRANSACTION_CARD_SCHEME_NOT_MATCHED = "TRANSACTION_CARD_SCHEME_NOT_MATCHED",
    TRANSACTION_CANCELED = "TRANSACTION_CANCELED",
    TRANSACTION_TIMEOUT = "TRANSACTION_TIMEOUT",
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
}

export enum CardProcess {
    WAITING_FOR_CARD = "CheckCardProcess_WAITING_FOR_CARD",
    SET_AMOUNT = "CheckCardProcess_SET_AMOUNT",
    PIN_ENTRY_ICC_CARD = "CheckCardProcess_PIN_ENTRY_ICC_CARD",
    PIN_ENTRY_MAG_CARD = "CheckCardProcess_PIN_ENTRY_MAG_CARD",
    SELECT_APPLICATION = "CheckCardProcess_SELECT_APPLICATION",
    WAITING_FOR_SWIPE_OR_INSERT = "CheckCardProcess_WAITING_FOR_SWIPE_OR_INSERT",
    WAITING_FOR_SWIPE = "CheckCardProcess_WAITING_FOR_SWIPE",
    WAITING_FOR_INSERT = "CheckCardProcess_WAITING_FOR_INSERT",
    WAITING_FOR_TAP = "CheckCardProcess_WAITING_FOR_TAP",
    WAITING_FOR_SWIPE_OR_TAP = "CheckCardProcess_WAITING_FOR_SWIPE_OR_TAP",
    WAITING_FOR_INSERT_OR_TAP = "CheckCardProcess_WAITING_FOR_INSERT_OR_TAP",
    WAITING_FOR_SWIPE_OR_INSERT_OR_TAP = "CheckCardProcess_WAITING_FOR_SWIPE_OR_INSERT_OR_TAP",
    WAITING_FOR_QRCODE = "CheckCardProcess_WAITING_FOR_QRCODE"
}

export enum Error {
    UNKNOWN = "UNKNOWN",
    CMD_NOT_AVAILABLE = "CMD_NOT_AVAILABLE",
    TIMEOUT = "TIMEOUT",
    DEVICE_BUSY = "DEVICE_BUSY",
    INPUT_OUT_OF_RANGE = "INPUT_OUT_OF_RANGE",
    INPUT_INVALID_FORMAT = "INPUT_INVALID_FORMAT",
    INPUT_INVALID = "INPUT_INVALID",
    CASHBACK_NOT_SUPPORTED = "CASHBACK_NOT_SUPPORTED",
    CRC_ERROR = "CRC_ERROR",
    COMM_ERROR = "COMM_ERROR",
    FAIL_TO_START_BT = "FAIL_TO_START_BT",
    VOLUME_WARNING_NOT_ACCEPTED = "VOLUME_WARNING_NOT_ACCEPTED",
    FAIL_TO_START_AUDIO = "FAIL_TO_START_AUDIO",
    INVALID_FUNCTION_IN_CURRENT_CONNECTION_MODE = "INVALID_FUNCTION_IN_CURRENT_CONNECTION_MODE",
    COMM_LINK_UNINITIALIZED = "COMM_LINK_UNINITIALIZED",
    BTV4_NOT_SUPPORTED = "BTV4_NOT_SUPPORTED",
    FAIL_TO_START_SERIAL = "FAIL_TO_START_SERIAL",
    USB_DEVICE_NOT_FOUND = "USB_DEVICE_NOT_FOUND",
    USB_DEVICE_PERMISSION_DENIED = "USB_DEVICE_PERMISSION_DENIED",
    USB_NOT_SUPPORTED = "USB_NOT_SUPPORTED",
    CHANNEL_BUFFER_FULL = "CHANNEL_BUFFER_FULL",
    BLUETOOTH_PERMISSION_DENIED = "BLUETOOTH_PERMISSION_DENIED",
    HARDWARE_NOT_SUPPORTED = "HARDWARE_NOT_SUPPORTED",
    TAMPER = "TAMPER",
    PCI_ERROR = "PCI_ERROR",
    AUDIO_PERMISSION_DENIED = "AUDIO_PERMISSION_DENIED",
    BLUETOOTH_LOCATION_PERMISSION_DENIED = "BLUETOOTH_LOCATION_PERMISSION_DENIED",
    SERIAL_PERMISSION_DENIED = "SERIAL_PERMISSION_DENIED"
}

export enum DisplayText {
    APPROVED = "APPROVED",
    CALL_YOUR_BANK = "CALL_YOUR_BANK",
    DECLINED = "DECLINED",
    ENTER_AMOUNT = "ENTER_AMOUNT",
    ENTER_PIN = "ENTER_PIN",
    INCORRECT_PIN = "INCORRECT_PIN",
    INSERT_CARD = "INSERT_CARD",
    NOT_ACCEPTED = "NOT_ACCEPTED",
    PIN_OK = "PIN_OK",
    PLEASE_WAIT = "PLEASE_WAIT",
    REMOVE_CARD = "REMOVE_CARD",
    USE_MAG_STRIPE = "USE_MAG_STRIPE",
    TRY_AGAIN = "TRY_AGAIN",
    REFER_TO_YOUR_PAYMENT_DEVICE = "REFER_TO_YOUR_PAYMENT_DEVICE",
    TRANSACTION_TERMINATED = "TRANSACTION_TERMINATED",
    PROCESSING = "PROCESSING",
    LAST_PIN_TRY = "LAST_PIN_TRY",
    PRESENT_CARD = "PRESENT_CARD",
    SELECT_ACCOUNT = "SELECT_ACCOUNT",
    APPROVED_PLEASE_SIGN = "APPROVED_PLEASE_SIGN",
    PRESENT_CARD_AGAIN = "PRESENT_CARD_AGAIN",
    AUTHORISING = "AUTHORISING",
    INSERT_SWIPE_OR_TRY_ANOTHER_CARD = "INSERT_SWIPE_OR_TRY_ANOTHER_CARD",
    INSERT_OR_SWIPE_CARD = "INSERT_OR_SWIPE_CARD",
    MULTIPLE_CARDS_DETECTED = "MULTIPLE_CARDS_DETECTED",
    TIMEOUT = "TIMEOUT",
    APPLICATION_EXPIRED = "APPLICATION_EXPIRED",
    FINAL_CONFIRM = "FINAL_CONFIRM",
    SHOW_THANK_YOU = "SHOW_THANK_YOU",
    PIN_TRY_LIMIT_EXCEEDED = "PIN_TRY_LIMIT_EXCEEDED",
    NOT_ICC_CARD = "NOT_ICC_CARD",
    CARD_INSERTED = "CARD_INSERTED",
    CARD_REMOVED = "CARD_REMOVED",
    NO_EMV_APPS = "NO_EMV_APPS",
    ENTER_PIN_BYPASS = "ENTER_PIN_BYPASS",
    LOW = "LOW",
    CRITICALLY_LOW = "CRITICALLY_LOW"
}

export enum TransactionResult {
    APPROVED = "APPROVED",
    TERMINATED = "TERMINATED",
    DECLINED = "DECLINED",
    CANCEL = "CANCEL",
    CAPK_FAIL = "CAPK_FAIL",
    NOT_ICC = "NOT_ICC",
    SELECT_APP_FAIL = "SELECT_APP_FAIL",
    DEVICE_ERROR = "DEVICE_ERROR",
    APPLICATION_BLOCKED = "APPLICATION_BLOCKED",
    ICC_CARD_REMOVED = "ICC_CARD_REMOVED",
    CARD_BLOCKED = "CARD_BLOCKED",
    CARD_NOT_SUPPORTED = "CARD_NOT_SUPPORTED",
    CONDITION_NOT_SATISFIED = "CONDITION_NOT_SATISFIED",
    INVALID_ICC_DATA = "INVALID_ICC_DATA",
    MISSING_MANDATORY_DATA = "MISSING_MANDATORY_DATA",
    NO_EMV_APPS = "NO_EMV_APPS",
    AUTO_REVERSAL_TRX = "AUTO_REVERSAL_TRX"
}

export enum CardSchemerResult {
    ICC_CARD = "ICC_CARD",
    MAG_CARD = "MAG_CARD",
    MAG_AMEXCARD = "MAG_AMEXCARD"
}

export enum TransactionType {
    GOODS = "GOODS",
    SERVICES = "SERVICES",
    CASHBACK = "CASHBACK",
    INQUIRY = "INQUIRY",
    TRANSFER = "TRANSFER",
    PAYMENT = "PAYMENT",
    REFUND = "REFUND",
    VOID = "VOID",
    REVERSAL = "REVERSAL"
}